### PR TITLE
[IMP] sale_project_user_profile: Changes for improve compatibility

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @leemannd , could you review this IMP please? Thanks!

**Comment by carlosdauden** [comment]
Feel free to remove my copyright

**Comment by leemannd** [comment]
@carlosdauden @rafaelbn First of all, Thanks for the feedbacks on the original PR and this improvement. I have first to check internally with my PM because:
 - As mentionned in the description, I'm not the author
 - The field `user_profile` was intended to be connected to `track_service` I have to see it with the PM

I'll come back to you ASAP.
@carlosdauden For me you worked on it to improve it. You deserve the copyright

**Review by gurneyalex — CHANGES_REQUESTED** [review]
Hello @carlosdauden 
I don't understand what you are trying to solve. What does "improve compatibility" mean? 

Can you split your commits between the refactoring of the code and the "compatiblity improvement" bit, this will make review easier. Also please explain the rationale if the second commit in the commit message, so that users of git blame will have a better chance of understanding what is being done here. 

Thanks

**Comment by carlosdauden** [comment]
@gurneyalex Changes done.

I Split in 2 commits, but in inverse order that you have said because it was more easy for me :innocent:

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by leemannd** [comment]
@pedrobaeza Alex wasn't here these last days. I'll ping him when he's back next week.

**Comment by pedrobaeza** [comment]
OK, thanks.

**Comment by gurneyalex** [comment]
@carlosdauden  @pedrobaeza  I still don't see where the compatibility is improved. Can you clarify?

**Comment by rafaelbn** [comment]
Please @carlosdauden try to clarify this in a way @gurneyalex can see our idea. Thanks

**Comment by pedrobaeza** [comment]
@gurneyalex @leemannd the problem with the approach of adding a new `track_service` value is that you need to overwrite every functionality that uses the value of that field for making the same thing. You have an example in your own code: https://github.com/OCA/sale-workflow/pull/537/files#diff-6acbc1ab8ca292d601e85b915278e821R33. You are copying the implementation of sale_timesheet. And there are a lot of similar incompatibilities due to this new value. For example, with module `sale_order_invoicing_finished_task`. You would need a glue module for this one to make it work.

With this other approach, having an extra boolean field, you let the standard system (or extensions) to work with the original values of `track_service`, but intercepting the interesting things. My colleague Carlos has pointed you a simple SQL for transitioning from the old module to the new one in the DBs where you have that old implementation installed:

```sql
UPDATE user_profile = True, track_service = 'timesheet' WHERE track_service='user_profile'
```

Please reconsider the approach for having a solid solution without the need of a lot of glue modules.

**Review by rafaelbn — APPROVED** [review]
@leemannd @carlosdauden tested and running in production environment 👍

**Comment by pedrobaeza** [comment]
@gurneyalex @leemannd I beg you to please merge this. It's not going to suppose you any problem, but covers our use case.

**Comment by rafaelbn** [comment]
@carlosdauden you could close this as the original PR was closed.

**Comment by rafaelbn** [comment]
This PR can be closed

**Pull request closed without merging**
